const mongoose = require('mongoose');
const Product = require('./Models/product'); // Adjust the path if necessary

// Replace with your actual MongoDB connection string
const dbURI = 'mongodb+srv://MyRoboMart:4a159Jb9L1yw09et@myrobomartcluster.cxyqw.mongodb.net/';
const products = [
  // Popular Products (9 items)
  {
    name: "Wireless Mouse",
    category: "Electronics",
    description: "A high-precision wireless mouse with ergonomic design.",
    imageUrl: "https://res.cloudinary.com/duyxiulgp/image/upload/v1726985066/61YX-zoj9JL._SX522_-removebg-preview_h45bby.png",
    imageUrls: [
      "https://res.cloudinary.com/duyxiulgp/image/upload/v1726985066/61YX-zoj9JL._SX522_-removebg-preview_h45bby.png",
      "https://res.cloudinary.com/duyxiulgp/image/upload/v1726985066/61YX-zoj9JL._SX522_-removebg-preview_h45bby.png",
      "https://res.cloudinary.com/duyxiulgp/image/upload/v1726985066/61YX-zoj9JL._SX522_-removebg-preview_h45bby.png",
      "https://res.cloudinary.com/duyxiulgp/image/upload/v1726985066/61YX-zoj9JL._SX522_-removebg-preview_h45bby.png",
      "https://res.cloudinary.com/duyxiulgp/image/upload/v1726985066/61YX-zoj9JL._SX522_-removebg-preview_h45bby.png",
      "https://res.cloudinary.com/duyxiulgp/image/upload/v1726985066/61YX-zoj9JL._SX522_-removebg-preview_h45bby.png",
    ],
    brand: "TechBrand",
    type: "Mouse",
    mfg: new Date("2023-01-01"),
    sku: "MOUSE123",
    tags: ["wireless", "mouse", "ergonomic"],
    stock: 50,
    rating: 4.5,
    price: 29.99,
    originalPrice: 39.99,
    discount: 25,
    badge: "Best Seller",
    badgeColor: "#FFD700",
    vendor: "TechVendor",
    specifications: [
      "Ergonomic design for comfort",
      "2.4 GHz wireless technology",
      "Battery life up to 12 months",
      "Adjustable DPI settings",
      "Compatible with Windows and Mac",
    ],
    suggestedUse: [
      "Office use",
      "Gaming",
      "Graphic design",
      "Daily tasks",
      "Remote work",
    ],
    warnings: [
      "Keep away from water",
      "Not suitable for children under 5",
      "Avoid exposure to extreme temperatures",
      "Use only as directed",
      "Do not disassemble",
    ],
    packageIncludes: ["Mouse", "USB receiver", "Batteries", "User manual"],
    warranty: "2 years",
    features: ["Wireless connectivity", "Compact size", "Easy to use"],
    additionalInfo: "Available in multiple colors.",
    isPopular: true,
    isDailySell: false,
    isDealOfTheDay: false,
    isTopSelling: false,
    isTrending: false,
    isRecentlyAdded: false,
    isTopRated: false,
  },
  {
    name: "Gaming Headset",
    category: "Electronics",
    description: "High-quality gaming headset with surround sound.",
    imageUrl: "https://res.cloudinary.com/duyxiulgp/image/upload/v1726985066/61YX-zoj9JL._SX522_-removebg-preview_h45bby.png",
    imageUrls: [
      "https://res.cloudinary.com/duyxiulgp/image/upload/v1726985066/61YX-zoj9JL._SX522_-removebg-preview_h45bby.png",
      "https://res.cloudinary.com/duyxiulgp/image/upload/v1726985066/61YX-zoj9JL._SX522_-removebg-preview_h45bby.png",
      "https://res.cloudinary.com/duyxiulgp/image/upload/v1726985066/61YX-zoj9JL._SX522_-removebg-preview_h45bby.png",
      "https://res.cloudinary.com/duyxiulgp/image/upload/v1726985066/61YX-zoj9JL._SX522_-removebg-preview_h45bby.png",
      "https://res.cloudinary.com/duyxiulgp/image/upload/v1726985066/61YX-zoj9JL._SX522_-removebg-preview_h45bby.png",
      "https://res.cloudinary.com/duyxiulgp/image/upload/v1726985066/61YX-zoj9JL._SX522_-removebg-preview_h45bby.png",
    ],
    brand: "GameBrand",
    type: "Headset",
    mfg: new Date("2023-01-01"),
    sku: "HEADSET123",
    tags: ["gaming", "headset", "audio"],
    stock: 30,
    rating: 4.7,
    price: 59.99,
    originalPrice: 79.99,
    discount: 25,
    badge: "Daily Deal",
    badgeColor: "#FF4500",
    vendor: "GameVendor",
    specifications: [
      "Noise-canceling microphone",
      "Comfortable ear pads",
      "Adjustable headband",
      "360° surround sound",
      "Compatible with PC and consoles",
    ],
    suggestedUse: [
      "Gaming",
      "Online meetings",
      "Listening to music",
      "Podcasts",
      "Video calls",
    ],
    warnings: [
      "Do not expose to moisture",
      "Avoid loud volumes for extended periods",
      "Not suitable for children under 6",
      "Handle with care",
      "Regularly clean ear pads",
    ],
    packageIncludes: ["Headset", "Audio cable", "User manual"],
    warranty: "1 year",
    features: ["Lightweight", "High-fidelity sound", "Flexible microphone"],
    additionalInfo: "Available in multiple colors.",
    isPopular: true,
    isDailySell: true,
    isDealOfTheDay: false,
    isTopSelling: false,
    isTrending: false,
    isRecentlyAdded: false,
    isTopRated: false,
  },
  {
    name: "Mechanical Keyboard",
    category: "Electronics",
    description: "Durable mechanical keyboard with customizable RGB lighting.",
    imageUrl: "https://res.cloudinary.com/duyxiulgp/image/upload/v1726985066/61YX-zoj9JL._SX522_-removebg-preview_h45bby.png",
    imageUrls: [
      "https://res.cloudinary.com/duyxiulgp/image/upload/v1726985066/61YX-zoj9JL._SX522_-removebg-preview_h45bby.png",
      "https://res.cloudinary.com/duyxiulgp/image/upload/v1726985066/61YX-zoj9JL._SX522_-removebg-preview_h45bby.png",
      "https://res.cloudinary.com/duyxiulgp/image/upload/v1726985066/61YX-zoj9JL._SX522_-removebg-preview_h45bby.png",
      "https://res.cloudinary.com/duyxiulgp/image/upload/v1726985066/61YX-zoj9JL._SX522_-removebg-preview_h45bby.png",
      "https://res.cloudinary.com/duyxiulgp/image/upload/v1726985066/61YX-zoj9JL._SX522_-removebg-preview_h45bby.png",
      "https://res.cloudinary.com/duyxiulgp/image/upload/v1726985066/61YX-zoj9JL._SX522_-removebg-preview_h45bby.png",
    ],
    brand: "KeyBrand",
    type: "Keyboard",
    mfg: new Date("2023-01-01"),
    sku: "KEYBOARD123",
    tags: ["mechanical", "keyboard", "RGB"],
    stock: 25,
    rating: 4.6,
    price: 89.99,
    originalPrice: 109.99,
    discount: 18,
    badge: "Top Rated",
    badgeColor: "#228B22",
    vendor: "KeyVendor",
    specifications: [
      "Customizable RGB lighting",
      "Cherry MX switches",
      "Full-size layout",
      "Anti-ghosting technology",
      "Durable construction",
    ],
    suggestedUse: [
      "Gaming",
      "Typing",
      "Office work",
      "Coding",
      "Creative tasks",
    ],
    warnings: [
      "Not waterproof",
      "Keep away from extreme heat",
      "Do not modify switches",
      "Avoid dropping",
      "Regularly clean to avoid dust buildup",
    ],
    packageIncludes: ["Keyboard", "USB cable", "User manual"],
    warranty: "1 year",
    features: ["Customizable keys", "Responsive feedback", "Durable keys"],
    additionalInfo: "Available in different switch types.",
    isPopular: true,
    isDailySell: false,
    isDealOfTheDay: false,
    isTopSelling: true,
    isTrending: false,
    isRecentlyAdded: false,
    isTopRated: true,
  },
  {
    name: "USB-C Hub",
    category: "Electronics",
    description: "Versatile USB-C hub with multiple ports for connectivity.",
    imageUrl: "https://res.cloudinary.com/duyxiulgp/image/upload/v1726985066/61YX-zoj9JL._SX522_-removebg-preview_h45bby.png",
    imageUrls: [
      "https://res.cloudinary.com/duyxiulgp/image/upload/v1726985066/61YX-zoj9JL._SX522_-removebg-preview_h45bby.png",
      "https://res.cloudinary.com/duyxiulgp/image/upload/v1726985066/61YX-zoj9JL._SX522_-removebg-preview_h45bby.png",
      "https://res.cloudinary.com/duyxiulgp/image/upload/v1726985066/61YX-zoj9JL._SX522_-removebg-preview_h45bby.png",
      "https://res.cloudinary.com/duyxiulgp/image/upload/v1726985066/61YX-zoj9JL._SX522_-removebg-preview_h45bby.png",
      "https://res.cloudinary.com/duyxiulgp/image/upload/v1726985066/61YX-zoj9JL._SX522_-removebg-preview_h45bby.png",
      "https://res.cloudinary.com/duyxiulgp/image/upload/v1726985066/61YX-zoj9JL._SX522_-removebg-preview_h45bby.png",
    ],
    brand: "HubBrand",
    type: "Hub",
    mfg: new Date("2023-01-01"),
    sku: "HUB123",
    tags: ["USB-C", "hub", "connectivity"],
    stock: 40,
    rating: 4.8,
    price: 39.99,
    originalPrice: 49.99,
    discount: 20,
    badge: "Trending",
    badgeColor: "#1E90FF",
    vendor: "HubVendor",
    specifications: [
      "3 USB 3.0 ports",
      "HDMI output",
      "SD and Micro SD card slots",
      "Fast charging capability",
      "Compact design",
    ],
    suggestedUse: [
      "Laptop connectivity",
      "Data transfer",
      "Media display",
      "Expanding device ports",
      "Photography",
    ],
    warnings: [
      "Use only with USB-C devices",
      "Avoid overheating",
      "Do not pull on cables",
      "Handle with care",
      "Not suitable for high power devices",
    ],
    packageIncludes: ["USB-C Hub", "USB-C cable", "User manual"],
    warranty: "1 year",
    features: ["Lightweight", "Portable", "Multiple ports"],
    additionalInfo: "Compatible with most devices.",
    isPopular: true,
    isDailySell: false,
    isDealOfTheDay: false,
    isTopSelling: false,
    isTrending: true,
    isRecentlyAdded: false,
    isTopRated: false,
  },
  {
    name: "Smartphone Stand",
    category: "Electronics",
    description: "Adjustable smartphone stand for comfortable viewing.",
    imageUrl: "https://res.cloudinary.com/duyxiulgp/image/upload/v1726985066/61YX-zoj9JL._SX522_-removebg-preview_h45bby.png",
    imageUrls: [
      "https://res.cloudinary.com/duyxiulgp/image/upload/v1726985066/61YX-zoj9JL._SX522_-removebg-preview_h45bby.png",
      "https://res.cloudinary.com/duyxiulgp/image/upload/v1726985066/61YX-zoj9JL._SX522_-removebg-preview_h45bby.png",
      "https://res.cloudinary.com/duyxiulgp/image/upload/v1726985066/61YX-zoj9JL._SX522_-removebg-preview_h45bby.png",
      "https://res.cloudinary.com/duyxiulgp/image/upload/v1726985066/61YX-zoj9JL._SX522_-removebg-preview_h45bby.png",
      "https://res.cloudinary.com/duyxiulgp/image/upload/v1726985066/61YX-zoj9JL._SX522_-removebg-preview_h45bby.png",
      "https://res.cloudinary.com/duyxiulgp/image/upload/v1726985066/61YX-zoj9JL._SX522_-removebg-preview_h45bby.png",
    ],
    brand: "StandBrand",
    type: "Stand",
    mfg: new Date("2023-01-01"),
    sku: "STAND123",
    tags: ["stand", "smartphone", "adjustable"],
    stock: 60,
    rating: 4.3,
    price: 19.99,
    originalPrice: 29.99,
    discount: 33,
    badge: "Best Value",
    badgeColor: "#FFA500",
    vendor: "StandVendor",
    specifications: [
      "Adjustable height and angle",
      "Non-slip base",
      "Lightweight and portable",
      "Compatible with most smartphones",
      "Durable material",
    ],
    suggestedUse: [
      "Watching videos",
      "Video calls",
      "Reading",
      "Cooking",
      "Desk organization",
    ],
    warnings: [
      "Not for use with heavy tablets",
      "Avoid placing in wet areas",
      "Handle with care",
      "Regularly clean to avoid dust buildup",
      "Do not overstress joints",
    ],
    packageIncludes: ["Smartphone Stand", "User manual"],
    warranty: "1 year",
    features: ["Compact", "Easy to use", "Adjustable design"],
    additionalInfo: "Available in various colors.",
    isPopular: true,
    isDailySell: false,
    isDealOfTheDay: false,
    isTopSelling: false,
    isTrending: false,
    isRecentlyAdded: false,
    isTopRated: true,
  },
  {
    name: "Portable Charger",
    category: "Electronics",
    description: "High-capacity portable charger for on-the-go charging.",
    imageUrl: "https://res.cloudinary.com/duyxiulgp/image/upload/v1726985066/61YX-zoj9JL._SX522_-removebg-preview_h45bby.png",
    imageUrls: [
      "https://res.cloudinary.com/duyxiulgp/image/upload/v1726985066/61YX-zoj9JL._SX522_-removebg-preview_h45bby.png",
      "https://res.cloudinary.com/duyxiulgp/image/upload/v1726985066/61YX-zoj9JL._SX522_-removebg-preview_h45bby.png",
      "https://res.cloudinary.com/duyxiulgp/image/upload/v1726985066/61YX-zoj9JL._SX522_-removebg-preview_h45bby.png",
      "https://res.cloudinary.com/duyxiulgp/image/upload/v1726985066/61YX-zoj9JL._SX522_-removebg-preview_h45bby.png",
      "https://res.cloudinary.com/duyxiulgp/image/upload/v1726985066/61YX-zoj9JL._SX522_-removebg-preview_h45bby.png",
      "https://res.cloudinary.com/duyxiulgp/image/upload/v1726985066/61YX-zoj9JL._SX522_-removebg-preview_h45bby.png",
    ],
    brand: "ChargeBrand",
    type: "Charger",
    mfg: new Date("2023-01-01"),
    sku: "CHARGER123",
    tags: ["portable", "charger", "power bank"],
    stock: 100,
    rating: 4.9,
    price: 29.99,
    originalPrice: 39.99,
    discount: 25,
    badge: "Best Seller",
    badgeColor: "#FFD700",
    vendor: "ChargeVendor",
    specifications: [
      "20,000 mAh capacity",
      "Fast charging",
      "Multiple USB ports",
      "LED battery indicator",
      "Compact and lightweight",
    ],
    suggestedUse: [
      "Traveling",
      "Camping",
      "Emergency charging",
      "Daily use",
      "Outdoor activities",
    ],
    warnings: [
      "Keep away from water",
      "Do not expose to high temperatures",
      "Use only with compatible devices",
      "Avoid overcharging",
      "Handle with care",
    ],
    packageIncludes: ["Portable Charger", "USB cable", "User manual"],
    warranty: "1 year",
    features: ["Fast charging", "High capacity", "Multiple ports"],
    additionalInfo: "Available in multiple colors.",
    isPopular: true,
    isDailySell: false,
    isDealOfTheDay: false,
    isTopSelling: true,
    isTrending: false,
    isRecentlyAdded: false,
    isTopRated: true,
  },
  {
    name: "Bluetooth Speaker",
    category: "Electronics",
    description: "Portable Bluetooth speaker with deep bass and long battery life.",
    imageUrl: "https://res.cloudinary.com/duyxiulgp/image/upload/v1726985066/61YX-zoj9JL._SX522_-removebg-preview_h45bby.png",
    imageUrls: [
      "https://res.cloudinary.com/duyxiulgp/image/upload/v1726985066/61YX-zoj9JL._SX522_-removebg-preview_h45bby.png",
      "https://res.cloudinary.com/duyxiulgp/image/upload/v1726985066/61YX-zoj9JL._SX522_-removebg-preview_h45bby.png",
      "https://res.cloudinary.com/duyxiulgp/image/upload/v1726985066/61YX-zoj9JL._SX522_-removebg-preview_h45bby.png",
      "https://res.cloudinary.com/duyxiulgp/image/upload/v1726985066/61YX-zoj9JL._SX522_-removebg-preview_h45bby.png",
      "https://res.cloudinary.com/duyxiulgp/image/upload/v1726985066/61YX-zoj9JL._SX522_-removebg-preview_h45bby.png",
      "https://res.cloudinary.com/duyxiulgp/image/upload/v1726985066/61YX-zoj9JL._SX522_-removebg-preview_h45bby.png",
    ],
    brand: "SpeakerBrand",
    type: "Speaker",
    mfg: new Date("2023-01-01"),
    sku: "SPEAKER123",
    tags: ["Bluetooth", "speaker", "audio"],
    stock: 75,
    rating: 4.6,
    price: 49.99,
    originalPrice: 69.99,
    discount: 29,
    badge: "Featured",
    badgeColor: "#FF4500",
    vendor: "SpeakerVendor",
    specifications: [
      "10 hours of playtime",
      "Bluetooth 5.0",
      "Water-resistant design",
      "Built-in microphone",
      "Compact size",
    ],
    suggestedUse: [
      "Outdoor parties",
      "Traveling",
      "Home use",
      "Workout sessions",
      "Picnics",
    ],
    warnings: [
      "Keep away from moisture",
      "Do not drop from heights",
      "Avoid exposing to extreme temperatures",
      "Use only as intended",
      "Regularly check for software updates",
    ],
    packageIncludes: ["Bluetooth Speaker", "USB charging cable", "User manual"],
    warranty: "1 year",
    features: ["Deep bass", "Portable", "Long battery life"],
    additionalInfo: "Available in various colors.",
    isPopular: true,
    isDailySell: false,
    isDealOfTheDay: true,
    isTopSelling: true,
    isTrending: true,
    isRecentlyAdded: false,
    isTopRated: true,
  },
  {
    name: "Wireless Earbuds",
    category: "Electronics",
    description: "True wireless earbuds with noise cancellation and touch controls.",
    imageUrl: "https://res.cloudinary.com/duyxiulgp/image/upload/v1726985066/61YX-zoj9JL._SX522_-removebg-preview_h45bby.png",
    imageUrls: [
      "https://res.cloudinary.com/duyxiulgp/image/upload/v1726985066/61YX-zoj9JL._SX522_-removebg-preview_h45bby.png",
      "https://res.cloudinary.com/duyxiulgp/image/upload/v1726985066/61YX-zoj9JL._SX522_-removebg-preview_h45bby.png",
      "https://res.cloudinary.com/duyxiulgp/image/upload/v1726985066/61YX-zoj9JL._SX522_-removebg-preview_h45bby.png",
      "https://res.cloudinary.com/duyxiulgp/image/upload/v1726985066/61YX-zoj9JL._SX522_-removebg-preview_h45bby.png",
      "https://res.cloudinary.com/duyxiulgp/image/upload/v1726985066/61YX-zoj9JL._SX522_-removebg-preview_h45bby.png",
      "https://res.cloudinary.com/duyxiulgp/image/upload/v1726985066/61YX-zoj9JL._SX522_-removebg-preview_h45bby.png",
    ],
    brand: "EarbudBrand",
    type: "Earbuds",
    mfg: new Date("2023-01-01"),
    sku: "EARBUD123",
    tags: ["wireless", "earbuds", "audio"],
    stock: 120,
    rating: 4.5,
    price: 59.99,
    originalPrice: 79.99,
    discount: 25,
    badge: "Hot Deal",
    badgeColor: "#FF6347",
    vendor: "EarbudVendor",
    specifications: [
      "Noise cancellation",
      "Touch controls",
      "5 hours of playtime",
      "Compact charging case",
      "Bluetooth connectivity",
    ],
    suggestedUse: [
      "Listening to music",
      "Making calls",
      "Working out",
      "Commuting",
      "Studying",
    ],
    warnings: [
      "Do not expose to moisture",
      "Avoid dropping",
      "Use at moderate volume",
      "Keep away from small children",
      "Regularly clean to avoid earwax buildup",
    ],
    packageIncludes: ["Wireless Earbuds", "Charging case", "User manual"],
    warranty: "1 year",
    features: ["Compact design", "Noise cancellation", "Touch controls"],
    additionalInfo: "Available in black and white.",
    isPopular: true,
    isDailySell: false,
    isDealOfTheDay: false,
    isTopSelling: true,
    isTrending: false,
    isRecentlyAdded: true,
    isTopRated: true,
  },
];

mongoose.connect(dbURI)
  .then(async () => {
    console.log('MongoDB connected');
    await Product.deleteMany({}); // Clear existing products (optional)
    await Product.insertMany(products);
    console.log('Products initialized successfully');
    mongoose.connection.close();
  })
  .catch(err => {
    console.error(err);
    mongoose.connection.close();
  });
